const projects = [
  {id:'P-001',name:'Рогунская ГЭС',sector:'Энергетика',region:'РРП',city:'Рогун',stage:'RFQ / тендер',pipeline:'Квалифицирован',score:96,confidence:'A',investment:'≈ $6,1 млрд',company:'ОАО «Рогунская ГЭС»',potential:'Силовые магистрали, машинный зал, инфраструктура и распределение большой мощности',fit:'Очень высокий',next:'Разделить объект на лоты; установить статус Lot 4 и закупок НКУ',source:'https://www.worldbank.org/en/programs/rogun-hydropower-plant-project',evidence:'Всемирный банк подтверждает продолжение строительных и электромеханических работ; в июне 2026 одобрено дополнительное финансирование $300 млн.',updated:'21.08.2026'},
  {id:'P-002',name:'Металлургический комплекс, Б. Гафуров',sector:'Металлургия',region:'Согд',city:'Бободжон Гафуров',stage:'Строительство',pipeline:'Квалифицирован',score:94,confidence:'A',investment:'≈ 6 млрд TJS',company:'ЗАО «Таджикский металлургический комбинат»',potential:'Непрерывное производство, печи, цеховые магистрали и высокие токи',fit:'Очень высокий',next:'Установить EPC, проектировщика электрики и окно закупки MEP',source:'https://www.president.tj/event/domestic_trips/56212',evidence:'Официальная публикация о строительстве промышленного комплекса и инвестициях около 6 млрд сомони.',updated:'09.07.2026'},
  {id:'P-003',name:'Crystal Green Glass — три завода',sector:'Стекло',region:'Душанбе',city:'Душанбе',stage:'Проектирование',pipeline:'Проверен',score:92,confidence:'A',investment:'≈ 1,2 млрд TJS',company:'ООО «Crystal Green Glass»',potential:'Печи, компрессоры, насосы и длинные производственные линии',fit:'Очень высокий',next:'Создать 3 подпроекта; запросить мощности и однолинейные схемы',source:'https://investcom.tj/presscenter/news/736-marosimi-baimzorasonii-sozishnomaoi-sarmojaguzor.html',evidence:'Инвестиционное соглашение охватывает производство кварца, листового и тарного стекла.',updated:'02.07.2026'},
  {id:'P-004',name:'Цементный завод, Истаравшан',sector:'Цемент',region:'Согд',city:'Истаравшан',stage:'Строительство',pipeline:'Квалифицирован',score:91,confidence:'A',investment:'1,2 млрд TJS',company:'ЗАО «Таджикский металлургический комбинат»',potential:'Дробилки, мельницы, печи, конвейеры и цеховое распределение',fit:'Очень высокий',next:'Установить EPC и электротехнического проектировщика',source:'https://www.president.tj/event/news/56175',evidence:'Официально заявлено строительство и ввод предприятия к 2029 году.',updated:'09.07.2026'},
  {id:'P-005',name:'Известковый завод, Б. Гафуров',sector:'Стройматериалы',region:'Согд',city:'Бободжон Гафуров',stage:'Строительство',pipeline:'Контакт',score:87,confidence:'A',investment:'Не раскрыто',company:'ЗАО «Таджикский металлургический комбинат»',potential:'Печи, дробление, аспирация и распределение по производственным участкам',fit:'Высокий',next:'Выход на SINOMA и техническую команду заказчика',source:'https://www.president.tj/event/news/56175',evidence:'SINOMA названа исполнителем проектирования, поставки, монтажа и пуска.',updated:'09.07.2026'},
  {id:'P-006',name:'Цементный завод «Сементи Точик»',sector:'Цемент',region:'РРП',city:'Варзоб',stage:'Строительство',pipeline:'Проверен',score:89,confidence:'A',investment:'Не раскрыто',company:'ООО «Сементи Точик»',potential:'Высокие токи и протяжённое распределение внутри производственного комплекса',fit:'Очень высокий',next:'Установить генподрядчика; срок проекта — 17 месяцев с 23.06.2026',source:'https://president.tj/event/news/55966',evidence:'Официально дан старт строительству второго цементного завода.',updated:'23.06.2026'},
  {id:'P-011',name:'Кластер текстильной промышленности',sector:'Текстиль',region:'Уточняется',city:'Таджикистан',stage:'Инвестсоглашение',pipeline:'Сигнал',score:84,confidence:'A',investment:'$83,2 млн',company:'ООО «Маркази рушди саноатӣ»',potential:'Полный цикл: прядение, ткачество, отделка; распределённые нагрузки и цеха',fit:'Высокий',next:'Уточнить площадки, очереди, проектировщика и график строительства',source:'https://investcom.tj/presscenter/news/745-marosimi-baimzorasonii-sozishnomai-sarmojaguzor-oid-ba-tasisi-kla.html',evidence:'15.07.2026 подписано соглашение на полный производственный цикл и более 5500 рабочих мест.',updated:'15.07.2026'},
  {id:'P-012',name:'Завод по переработке сурьмы',sector:'Горнодобыча',region:'Согд',city:'Айни',stage:'Инвестсоглашение',pipeline:'Сигнал',score:83,confidence:'A',investment:'$35 млн',company:'ОАО «Паҳндара майнинг»',potential:'Обогащение и переработка руды — энергоёмкие технологические линии',fit:'Высокий',next:'Получить технологическую схему, мощность и EPC-контакты',source:'https://investcom.tj/presscenter/news/736-marosimi-baimzorasonii-sozishnomaoi-sarmojaguzor.html',evidence:'Государственный комитет подтверждает инвестиционное соглашение и объём инвестиций.',updated:'02.07.2026'},
  {id:'P-013',name:'Солнечная программа «Руфтоб»',sector:'Энергетика',region:'Вся страна',city:'Таджикистан',stage:'Инвестсоглашение',pipeline:'Сигнал',score:73,confidence:'A',investment:'Не раскрыто',company:'ООО «Руфтоб»',potential:'Прямое применение зависит от промышленных площадок; сильный канал доступа к энергоёмким клиентам',fit:'Средний / контактный',next:'Получить список первых площадок и параметры присоединения',source:'https://investcom.tj/presscenter/news/700-baimzorasonii-sozishnomai-sarmojaguzor.html',evidence:'Соглашение предусматривает оснащение предприятий солнечными панелями суммарной мощностью 2000 МВт.',updated:'06.05.2026'},
  {id:'P-014',name:'Промышленный городок Suntiles',sector:'Стройматериалы',region:'Душанбе',city:'Душанбе',stage:'Расширение',pipeline:'Проверен',score:82,confidence:'A',investment:'Не раскрыто',company:'ЗАО «Сантайлс»',potential:'Несколько производств на единой площадке, керамические печи и распределение',fit:'Высокий',next:'Установить 3 строящихся объекта и планы расширения электроснабжения',source:'https://www.president.tj/event/news/53261',evidence:'Открыты три крупных предприятия и заложены ещё три производственных объекта.',updated:'20.10.2025'},
  {id:'P-007',name:'Darya AI — дата-центр',sector:'ЦОД',region:'ГБАО',city:'Дарвоз',stage:'Введён / расширение',pipeline:'Контакт',score:78,confidence:'A',investment:'Не раскрыто',company:'Darya AI',potential:'Резервируемое распределение, UPS, высокая плотность нагрузки',fit:'Высокий при расширении',next:'Проверить планы второй очереди и текущую архитектуру питания',source:'https://president.tj/event/news/51364',evidence:'Официально подтверждён ввод центра в 2025 году; расширение пока является гипотезой.',updated:'25.06.2025'},
  {id:'P-008',name:'InterContinental Opera Dushanbe',sector:'Гостиницы',region:'Душанбе',city:'Душанбе',stage:'Планируется',pipeline:'Сигнал',score:76,confidence:'B',investment:'Не раскрыто',company:'Собственник уточняется',potential:'Вертикальные магистрали, HVAC, кухня, общественные зоны',fit:'Высокий',next:'Подтвердить девелопера, MEP-проектировщика и дату закупки',source:'https://cmwp.uz/images/ENG_Central_Asian%20Hotel_Chains_Final_Presentation.pdf',evidence:'Объект присутствует в отраслевом обзоре гостиничного pipeline; участники требуют подтверждения.',updated:'26.08.2026'},
  {id:'P-015',name:'Клиника Shox Med',sector:'Здравоохранение',region:'Душанбе',city:'Душанбе',stage:'Строительство',pipeline:'Сигнал',score:74,confidence:'A',investment:'Не раскрыто',company:'Shox Med',potential:'Критические нагрузки, резервирование, медицинское оборудование и HVAC',fit:'Высокий',next:'Установить генподрядчика и MEP-проектировщика',source:'https://www.president.tj/event/news/54970',evidence:'Официально дан старт строительству клиники в Душанбе в марте 2026 года.',updated:'26.03.2026'},
  {id:'P-016',name:'Расширение производства Artel',sector:'Промышленность',region:'Уточняется',city:'Таджикистан',stage:'Строительство',pipeline:'Сигнал',score:72,confidence:'A',investment:'Не раскрыто',company:'Artel',potential:'Сборочные линии и распределение по производственным участкам',fit:'Средний / высокий',next:'Уточнить площадку, мощности и график комплектации',source:'https://www.president.tj/event/news/54970',evidence:'В марте 2026 года объявлено начало расширения линии бытовой техники.',updated:'26.03.2026'},
  {id:'P-017',name:'Цифровая инфраструктура госорганов',sector:'ЦОД',region:'Душанбе',city:'Душанбе',stage:'Реализация',pipeline:'Проверен',score:77,confidence:'A',investment:'Проект WB',company:'Государственные ведомства / WB',potential:'Дата-центр, резервирование и масштабируемое распределение электроэнергии',fit:'Высокий',next:'Определить площадку ЦОД и пакет закупок инфраструктуры',source:'https://documents1.worldbank.org/curated/en/099100225083013948/pdf/P506611-c319e9e3-0b4d-494f-acf6-510d538d5385.pdf',evidence:'Проект Digital Foundations предусматривает миграцию ведомств в поддерживаемый проектом дата-центр.',updated:'26.09.2025'},
  {id:'P-018',name:'Dushanbe Mall — высотный mixed-use комплекс',sector:'Высотные здания',region:'Душанбе',city:'Душанбе',stage:'Проектирование',pipeline:'Сигнал',score:93,confidence:'B',investment:'Не раскрыто',company:'Amir Holding',potential:'77 этажей, офисы, гостиница, жильё и retail: вертикальные магистрали, высокая плотность нагрузки, резервирование',fit:'Очень высокий',next:'Подтвердить разрешения, график строительства, MEP-проектировщика и электрические нагрузки',source:'https://www.amirholding.tj/en/projects/dushanbe-mall/',evidence:'Девелопер заявляет mixed-use комплекс площадью 3 000 000 м² с 77-этажной башней высотой 359 м; стадия требует независимого подтверждения.',updated:'27.08.2026'},
  {id:'P-019',name:'400-метровая башня в городском парке',sector:'Высотные здания',region:'Душанбе',city:'Душанбе',stage:'Концепция',pipeline:'Сигнал',score:88,confidence:'B',investment:'Не раскрыто',company:'Заказчик уточняется / RMJM',potential:'Офисные, жилые и коммерческие зоны, sky lobby, подземная инфраструктура и сверхвысокие вертикальные магистрали',fit:'Очень высокий',next:'Установить заказчика, площадку, статус согласований и сроки реализации',source:'https://rmjm.com/dushanbe-unveils-400m-tower-set-within-a-living-park-a-new-benchmark-for-urban-nature-integration/',evidence:'Архитектурное бюро RMJM представило концепцию 400-метровой многофункциональной башни в Душанбе в мае 2025 года.',updated:'22.05.2025'},
  {id:'P-020',name:'Pamir Business Center',sector:'Бизнес-центры',region:'Душанбе',city:'Душанбе',stage:'Проектирование',pipeline:'Сигнал',score:84,confidence:'B',investment:'Не раскрыто',company:'Amir Holding',potential:'Офисные площади, HVAC, лифты, IT-нагрузки и масштабируемое распределение',fit:'Высокий',next:'Подтвердить площадь активной очереди, стадию, генподрядчика и MEP',source:'https://www.amirholding.tj/en/projects/',evidence:'В портфеле девелопера указан многофункциональный Pamir Business Center площадью 24 000 м².',updated:'27.08.2026'},
  {id:'P-021',name:'Somoni Plaza',sector:'Бизнес-центры',region:'Душанбе',city:'Душанбе',stage:'Проектирование',pipeline:'Сигнал',score:83,confidence:'B',investment:'Не раскрыто',company:'Amir Holding',potential:'Многофункциональный объект: офисы, коммерция, вертикальное распределение и резервное питание',fit:'Высокий',next:'Проверить разрешения, активность стройплощадки и электротехническую спецификацию',source:'https://www.amirholding.tj/en/projects/',evidence:'Девелопер публикует проект многофункционального комплекса Somoni Plaza площадью 36 500 м² на проспекте Рудаки.',updated:'27.08.2026'},
  {id:'P-022',name:'Amir Residence',sector:'Высотные здания',region:'Душанбе',city:'Душанбе',stage:'Проектирование',pipeline:'Сигнал',score:76,confidence:'B',investment:'Не раскрыто',company:'Amir Holding',potential:'Жилой комплекс с общедомовыми нагрузками, лифтами, HVAC и коммерческими помещениями',fit:'Средний / высокий',next:'Уточнить этажность, сроки, генподрядчика и схему электроснабжения',source:'https://www.amirholding.tj/en/projects/',evidence:'В официальном портфеле девелопера указан жилой комплекс площадью 28 000 м² в районе Исмоили Сомони.',updated:'27.08.2026'},
  {id:'P-023',name:'Navruz Park',sector:'Высотные здания',region:'Душанбе',city:'Душанбе',stage:'Проектирование',pipeline:'Сигнал',score:75,confidence:'B',investment:'Не раскрыто',company:'Amir Holding',potential:'Распределение по корпусам, лифтовые и инженерные нагрузки, коммерческие зоны',fit:'Средний / высокий',next:'Подтвердить этажность, очередь строительства и MEP-команду',source:'https://www.amirholding.tj/en/projects/',evidence:'Девелопер публикует жилой комплекс Navruz Park площадью 31 000 м² в районе Фирдавси.',updated:'27.08.2026'},
  {id:'P-024',name:'Корпус обработки фруктов',sector:'Пищевая промышленность',region:'Согд',city:'Уточняется',stage:'Строительство',pipeline:'Сигнал',score:78,confidence:'A',investment:'Не раскрыто',company:'Таджикско-узбекский проект',potential:'Холодильное оборудование, конвейеры, упаковочные линии и распределённые производственные нагрузки',fit:'Высокий',next:'Установить юридическое лицо, площадку, мощность и поставщика технологической линии',source:'https://www.president.tj/event/news/54970',evidence:'Официально объявлен старт современной линии переработки фруктов в составе семи совместных проектов.',updated:'26.03.2026'},
  {id:'P-025',name:'Производство медицинских растворов',sector:'Фармацевтика',region:'Уточняется',city:'Таджикистан',stage:'Строительство',pipeline:'Сигнал',score:80,confidence:'A',investment:'Не раскрыто',company:'Таджикско-узбекский проект',potential:'Чистые помещения, HVAC, непрерывные линии, резервирование и повышенные требования к надёжности',fit:'Высокий',next:'Установить площадку, инициатора, проектировщика и требования к резервированию',source:'https://www.president.tj/event/news/54970',evidence:'Официальная публикация подтверждает начало проекта производства медицинских растворов.',updated:'26.03.2026'},
  {id:'P-026',name:'Производство мебели и промышленной техники',sector:'Промышленность',region:'Согд',city:'Уточняется',stage:'Строительство',pipeline:'Сигнал',score:76,confidence:'A',investment:'Не раскрыто',company:'Таджикско-узбекский проект',potential:'Станочные линии, аспирация, компрессоры и цеховое электроснабжение',fit:'Средний / высокий',next:'Разделить направления на подпроекты и установить площадки и мощности',source:'https://www.president.tj/event/news/54970',evidence:'Главы государств дали старт проектам производства мебели и промышленной техники в Согдийской области.',updated:'26.03.2026'},
  {id:'P-027',name:'Завод обогащения бентонита и каолина',sector:'Горнодобыча',region:'Согд',city:'Бободжон Гафуров',stage:'Подготовка',pipeline:'Сигнал',score:85,confidence:'A',investment:'Не раскрыто',company:'ЗАО «Таджикский металлургический комбинат»',potential:'Дробление, обогащение, сушильные линии и распределение большой мощности',fit:'Высокий',next:'Определить EPC, график проектирования и параметры электроснабжения',source:'https://www.president.tj/event/domestic_trips/56212',evidence:'Официально заявлен завод мощностью 160 тыс. тонн в год как часть металлургического кластера 2025–2029.',updated:'09.07.2026'},
  {id:'P-028',name:'Энергетический центр металлургического кластера',sector:'Энергетика',region:'Согд',city:'Бободжон Гафуров',stage:'Подготовка',pipeline:'Сигнал',score:90,confidence:'A',investment:'Не раскрыто',company:'ЗАО «Таджикский металлургический комбинат»',potential:'Центр генерации 90 МВт и распределение энергии между семью промышленными предприятиями',fit:'Очень высокий',next:'Установить проектировщика энергоцентра, топологию сети и границы поставки',source:'https://www.president.tj/event/domestic_trips/56212',evidence:'Официальная программа кластера включает энергоцентр мощностью 90 МВт с использованием технологического тепла.',updated:'09.07.2026'}
];

const sources=[
 {name:'Президент Республики Таджикистан',type:'Государственный',grade:'A',desc:'Открытия, закладка новых объектов, поручения и официальные сведения об инвесторах.',url:'https://www.president.tj/',count:9,icon:'RT'},
 {name:'Комитет по инвестициям',type:'Государственный',grade:'A',desc:'Инвестиционные соглашения, государственный портфель и сведения о частных инициаторах.',url:'https://investcom.tj/',count:5,icon:'КИ'},
 {name:'Всемирный банк',type:'МФО',grade:'A',desc:'Проектные документы, закупки, финансирование, исполнители и отчёты по реализации.',url:'https://www.worldbank.org/en/country/tajikistan',count:3,icon:'WB'},
 {name:'AIIB',type:'МФО',grade:'A',desc:'Финансирование инфраструктуры и мониторинговые отчёты по крупным энергопроектам.',url:'https://www.aiib.org/en/projects/list/year/All/member/Tajikistan',count:2,icon:'AI'},
 {name:'EBRD',type:'МФО',grade:'A',desc:'Стратегия страны, закупки и проекты частного сектора и инфраструктуры.',url:'https://www.ebrd.com/home/what-we-do/where-we-invest/tajikistan.html',count:1,icon:'EB'},
 {name:'CMWP Central Asia',type:'Отраслевой обзор',grade:'B',desc:'Гостиничный pipeline и проекты коммерческой недвижимости Центральной Азии.',url:'https://cmwp.uz/',count:1,icon:'CM'},
 {name:'Amir Holding',type:'Частный девелопер',grade:'B',desc:'Высотные, жилые, офисные и многофункциональные проекты в Душанбе.',url:'https://www.amirholding.tj/en/projects/',count:5,icon:'AH'},
 {name:'RMJM',type:'Архитектурное бюро',grade:'B',desc:'Проектная концепция 400-метровой многофункциональной башни в Душанбе.',url:'https://rmjm.com/dushanbe-unveils-400m-tower-set-within-a-living-park-a-new-benchmark-for-urban-nature-integration/',count:1,icon:'RM'},
 {name:'FG Group',type:'Системный интегратор',grade:'B',desc:'Локальный рынок инженерной и вычислительной инфраструктуры дата-центров.',url:'https://www.fg-group.tj/en/services/cod',count:1,icon:'FG'}
];

const customerContacts = [
 {key:'rogun',name:'Сановбар Шерова',initials:'СШ',role:'Представитель по связям с общественностью',company:'ГРП энергетических сооружений',phone:'+992 37 235 74 16',email:'esia.rogun.hpp@gmail.com',source:'https://rogunges.tj/wp-content/uploads/2025/08/rogun-hpp-esia-non-technical-summary_rus.pdf'},
 {key:'industry',name:'Абубакр Пиров',initials:'АП',role:'Начальник управления горной промышленности',company:'Минпром новых технологий РТ',phone:'+992 930 88 01 52',email:'mining.industry@sanoat.tj',source:'https://tajikistanmining.com/contacts'},
 {key:'invest',name:'Хуршедаи Кодир',initials:'ХК',role:'Заместитель председателя',company:'Госкоминвест РТ',phone:'+992 37 221 81 50',email:'info@investcom.tj',source:'https://investcom.tj/138-wg-members.html'},
 {key:'darya',name:'Контакт проекта Darya AI',initials:'DA',role:'Официальный канал проекта',company:'ООО «Дарёи санаи марказ»',phone:'+992 933 11 30 55',email:'kristina@greendarya.ai',source:'https://it-park.tj/en/darya-ai-en/'},
 {key:'amir',name:'Отдел по работе с партнёрами',initials:'AH',role:'Официальный контакт девелопера',company:'Amir Holding',phone:'+992 41 100 00 30',email:'info@amirholding.tj',source:'https://www.amirholding.tj/ru/'},
 {key:'artel',name:'Отдел международного сотрудничества',initials:'AR',role:'Официальный контакт производителя',company:'Artel',phone:'+998 71 202 77 88',email:'export@artelelectronics.com',source:'https://info.artelgroup.org/'},
 {key:'ihg',name:'Команда развития IHG',initials:'IHG',role:'Официальный канал гостиничного развития',company:'IHG Hotels & Resorts',phone:'',email:'',source:'https://development.ihg.com/contact-us'},
 {key:'shox',name:'Shox Med Center — контактный центр',initials:'SM',role:'Официальный контакт сети клиник',company:'Shox Med Center',phone:'+998 71 202 02 12',email:'info@shox.hospital',source:'https://shox.hospital/vrachi/eng'},
 {key:'digital',name:'Маджиди Юсуф',initials:'МЮ',role:'Контакт заёмщика / получателя проекта',company:'Республика Таджикистан',phone:'',email:'majidovyusuf@gmail.com',source:'https://documents1.worldbank.org/curated/en/099102124222544081/pdf/P506611-b5d7ae8e-0f19-4ebc-b9fa-fe3fd55d7015.pdf'},
 {key:'rmjm',name:'RMJM Dubai — проектная команда',initials:'RM',role:'Официальный проектный канал архитекторов',company:'RMJM Dubai',phone:'+971 4 563 88 88',email:'info@rmjmd3.com',source:'https://rmjm.com/contact-us/'},
 {key:'general',name:'Приёмная инвестиционных проектов',initials:'ГК',role:'Официальный государственный канал',company:'Госкоминвест РТ',phone:'+992 37 221 86 59',email:'info@investcom.tj',source:'https://investcom.tj/'}
];

const meetingPlan = [
 {projectId:'P-001',date:'02.09.2026',time:'10:00',format:'Онлайн',status:'Контакт установлен',owner:'Фаррух Саидов',objective:'Уточнить статус Lot 4 и график закупок НКУ',agenda:'Лоты, электрические нагрузки, сроки RFQ и техническая документация'},
 {projectId:'P-028',date:'04.09.2026',time:'11:30',format:'Выездная',status:'К назначению',owner:'Далер Назаров',objective:'Войти в проект энергоцентра на стадии подготовки',agenda:'Топология сети 90 МВт, границы поставки и проектировщик'},
 {projectId:'P-003',date:'07.09.2026',time:'14:00',format:'Онлайн',status:'К назначению',owner:'Мадина Рахмонова',objective:'Разделить комплекс на три закупочных пакета',agenda:'Мощности заводов, однолинейные схемы и календарь MEP'},
 {projectId:'P-018',date:'09.09.2026',time:'10:30',format:'Офис заказчика',status:'Подготовка',owner:'Фаррух Саидов',objective:'Подтвердить активную очередь Dushanbe Mall',agenda:'Разрешения, вертикальные магистрали, генподрядчик и MEP'},
 {projectId:'P-006',date:'11.09.2026',time:'09:30',format:'Выездная',status:'Подготовка',owner:'Далер Назаров',objective:'Определить окно комплектации цементного завода',agenda:'Генподрядчик, мощность, трассы и сроки поставки шинопровода'},
 {projectId:'P-015',date:'14.09.2026',time:'15:00',format:'Онлайн',status:'К назначению',owner:'Мадина Рахмонова',objective:'Выйти на техническую команду новой клиники',agenda:'Резервирование, критические нагрузки, HVAC и медицинское оборудование'},
 {projectId:'P-017',date:'16.09.2026',time:'11:00',format:'Офис заказчика',status:'К назначению',owner:'Зарина Юсуфова',objective:'Уточнить пакет закупок инфраструктуры ЦОД',agenda:'Площадка, схема резервирования, процедуры WB и сроки тендера'},
 {projectId:'P-019',date:'18.09.2026',time:'13:00',format:'Онлайн',status:'Предварительный контакт',owner:'Фаррух Саидов',objective:'Установить заказчика и статус реализации башни',agenda:'Площадка, согласования, команда проекта и вертикальное электроснабжение'}
];

const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('ru-RU').format(n);
function customerContact(project){
 if(project.id==='P-001')return customerContacts.find(c=>c.key==='rogun');
 if(['P-002','P-004','P-005','P-006','P-012','P-027','P-028'].includes(project.id))return customerContacts.find(c=>c.key==='industry');
 if(['P-003','P-011','P-013','P-014','P-024','P-025','P-026'].includes(project.id))return customerContacts.find(c=>c.key==='invest');
 if(project.id==='P-007')return customerContacts.find(c=>c.key==='darya');
 if(['P-018','P-020','P-021','P-022','P-023'].includes(project.id))return customerContacts.find(c=>c.key==='amir');
 if(project.id==='P-016')return customerContacts.find(c=>c.key==='artel');
 if(project.id==='P-008')return customerContacts.find(c=>c.key==='ihg');
 if(project.id==='P-015')return customerContacts.find(c=>c.key==='shox');
 if(project.id==='P-017')return customerContacts.find(c=>c.key==='digital');
 if(project.id==='P-019')return customerContacts.find(c=>c.key==='rmjm');
 return customerContacts.find(c=>c.key==='general');
}
function projectsForCustomer(contact){return projects.filter(project=>customerContact(project).key===contact.key)}
function customerContactMarkup(contact,compact=false){
 const phone=contact.phone?`<a href="tel:${contact.phone.replaceAll(' ','')}"${compact?' onclick="event.stopPropagation()"':''}>${contact.phone}</a>`:'';
 const email=contact.email?`<a href="mailto:${contact.email}"${compact?' onclick="event.stopPropagation()"':''}>${contact.email}</a>`:'';
 const source=`<a href="${contact.source}" target="_blank" rel="noopener"${compact?' onclick="event.stopPropagation()"':''}>Официальный источник ↗</a>`;
 if(compact)return `<div class="project-contact"><span class="project-contact-avatar">${contact.initials}</span><p><small>СО СТОРОНЫ ЗАКАЗЧИКА</small><b>${contact.name}</b>${phone}${email}${!phone&&!email?source:''}</p></div>`;
 return `<div class="dialog-contact"><span class="contact-avatar">${contact.initials}</span><p><b>${contact.name}</b><small>${contact.role} · ${contact.company}</small>${phone}${email}${source}</p></div>`;
}
function init(){
 const highCount=projects.filter(p=>p.score>=80).length, averageScore=Math.round(projects.reduce((sum,p)=>sum+p.score,0)/projects.length), actionCount=projects.filter(p=>['Сигнал','Проверен'].includes(p.pipeline)).length;
 qs('#navCount').textContent=projects.length;qs('#meetingNavCount').textContent=meetingPlan.length;qs('#contactNavCount').textContent=customerContacts.filter(c=>projectsForCustomer(c).length).length;qs('#mapProjectCount').textContent=projects.length;qs('#sourceCount').textContent=sources.length;
 qs('#landingProjectCount').textContent=projects.length;qs('#landingHighCount').textContent=highCount;qs('#landingSourceCount').textContent=sources.length;qs('#demoProjectCount').textContent=projects.length;qs('#demoAverageScore').textContent=averageScore;qs('#demoActionCount').textContent=actionCount;
 renderMetrics();renderTop();renderMiniPipeline();renderSignals();buildFilters();renderProjects();renderKanban();renderMeetings();renderContacts();renderSources();bind();route();
}
function renderMetrics(){const data=[['Активные проекты',projects.length,'+6 новых сигналов','◇'],['Высокий потенциал',projects.filter(p=>p.score>=80).length,'≥ 80 баллов','↗'],['Средний балл',Math.round(projects.reduce((a,p)=>a+p.score,0)/projects.length),'из 100','◎'],['Требуют действия',projects.filter(p=>['Сигнал','Проверен'].includes(p.pipeline)).length,'следующий шаг','!']];qs('#metrics').innerHTML=data.map((x,i)=>`<article class="metric-card"><div class="metric-top"><span>${x[0]}</span><span class="metric-icon">${x[3]}</span></div><strong>${x[1]}</strong><span class="delta ${i===3?'warn':''}">${x[2]}</span></article>`).join('')}
function renderTop(){qs('#topProjects').innerHTML=[...projects].sort((a,b)=>b.score-a.score).slice(0,5).map(p=>`<div class="opportunity" data-id="${p.id}" role="button" tabindex="0" aria-label="Открыть проект ${p.name}"><div class="score-ring" style="--score:${p.score}"><b>${p.score}</b></div><div><h3>${p.name}</h3><p>${p.city} · ${p.sector}</p></div><div class="amount"><b>${p.investment}</b><small>${p.stage}</small></div></div>`).join('')}
function renderMiniPipeline(){let stages=['Сигнал','Проверен','Квалифицирован','Контакт'];qs('#miniPipeline').innerHTML=stages.map(s=>{let n=projects.filter(p=>p.pipeline===s).length;return `<div class="pipeline-row"><span>${s}</span><div class="bar"><i style="width:${Math.max(10,n/projects.length*160)}%"></i></div><b>${n}</b></div>`}).join('')}
function renderSignals(){const stamp=d=>{let [day,month,year]=d.split('.').map(Number);return new Date(year,month-1,day)};let recent=[...projects].sort((a,b)=>stamp(b.updated)-stamp(a.updated)).slice(0,5);qs('#signalFeed').innerHTML=recent.map(p=>`<div class="signal"><span class="signal-icon">${p.confidence==='A'?'✓':'?'}</span><div><h3>${p.name}</h3><p>${p.evidence.slice(0,95)}… · ${p.updated}</p></div></div>`).join('')}
function buildFilters(){[['#sectorFilter','sector'],['#regionFilter','region'],['#statusFilter','stage']].forEach(([el,key])=>{[...new Set(projects.map(p=>p[key]))].sort().forEach(v=>qs(el).insertAdjacentHTML('beforeend',`<option value="${v}">${v}</option>`))})}
function filtered(){let term=qs('#projectSearch').value.trim().toLowerCase(), g=qs('#globalSearch').value.trim().toLowerCase();term=term||g;const selectedRegion=qs('#regionFilter').value;const allRegions=selectedRegion==='all'||selectedRegion==='Вся страна';return projects.filter(p=>(!term||Object.values(p).join(' ').toLowerCase().includes(term))&&(qs('#sectorFilter').value==='all'||p.sector===qs('#sectorFilter').value)&&(allRegions||p.region===selectedRegion)&&(qs('#statusFilter').value==='all'||p.stage===qs('#statusFilter').value))}
function renderProjects(){let list=filtered().sort((a,b)=>b.score-a.score);qs('#resultCount').textContent=list.length;qs('#emptyState').style.display=list.length?'none':'block';qs('#projectGrid').innerHTML=list.map(p=>{let c=customerContact(p);return `<article class="project-card" data-id="${p.id}" role="button" tabindex="0" aria-label="Открыть проект ${p.name}"><div class="card-top"><span class="sector">${p.sector}</span><span class="confidence">${p.confidence}</span></div><h3>${p.name}</h3><p class="meta">⌖ ${p.city} · ${p.company}</p><div class="potential"><span>ПОТЕНЦИАЛ KLM</span><b>${p.potential}</b></div><div class="card-footer"><span class="stage">${p.stage}</span><span class="project-score">${p.score}/100</span></div><p class="next-step">→ ${p.next}</p>${customerContactMarkup(c,true)}</article>`}).join('');bindProjectCards()}
function renderKanban(){let stages=['Сигнал','Проверен','Квалифицирован','Контакт'];qs('#kanban').innerHTML=stages.map(s=>{let list=projects.filter(p=>p.pipeline===s);return `<div class="kanban-col"><div class="kanban-head">${s}<span>${list.length}</span></div>${list.map(p=>`<div class="kanban-card" data-id="${p.id}" role="button" tabindex="0" aria-label="Открыть проект ${p.name}"><b>${p.name}</b><p>${p.company}</p><p>Следующий шаг: ${p.next}</p><div class="progress"><i style="width:${p.score}%"></i></div></div>`).join('')}</div>`}).join('');bindProjectCards()}
function renderSources(){qs('#sourcesGrid').innerHTML=sources.map(s=>`<article class="source-card"><div class="source-logo">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="source-meta"><span>${s.type} · Класс ${s.grade} · ${s.count} сигналов</span><a href="${s.url}" target="_blank" rel="noopener">Открыть ↗</a></div></article>`).join('')}
function renderContacts(){let term=qs('#contactSearch').value.trim().toLowerCase();let list=customerContacts.map(c=>({...c,projects:projectsForCustomer(c)})).filter(c=>c.projects.length&&(!term||[...Object.values(c),...c.projects.map(p=>p.name)].join(' ').toLowerCase().includes(term)));qs('#contactCount').textContent=list.length;qs('#contactsGrid').innerHTML=list.map(c=>{let phone=c.phone?`<a href="tel:${c.phone.replaceAll(' ','')}">${c.phone}</a>`:'',email=c.email?`<a href="mailto:${c.email}">Написать →</a>`:'';return `<article class="contact-card"><div class="contact-head"><span class="contact-avatar">${c.initials}</span><span class="contact-status">✓ Публичный контакт</span></div><h3>${c.name}</h3><p class="contact-role">${c.role}</p><div class="contact-details"><span><small>ОРГАНИЗАЦИЯ</small><b>${c.company}</b></span><span><small>ПРОЕКТОВ</small><b>${c.projects.length}</b></span></div><p class="contact-focus">${c.projects.map(p=>p.name).join(' · ')}</p><div class="contact-actions">${phone}${email}</div><a class="contact-source" href="${c.source}" target="_blank" rel="noopener">Проверить официальный источник ↗</a></article>`}).join('')}
function renderMeetings(){
 const confirmed=meetingPlan.filter(m=>m.status==='Контакт установлен').length;
 const preparing=meetingPlan.filter(m=>m.status==='Подготовка').length;
 qs('#meetingSummary').innerHTML=`<article><small>ЗАПЛАНИРОВАНО</small><b>${meetingPlan.length}</b><span>встреч на сентябрь</span></article><article><small>КОНТАКТ УСТАНОВЛЕН</small><b>${confirmed}</b><span>готово к подтверждению</span></article><article><small>В ПОДГОТОВКЕ</small><b>${preparing}</b><span>нужны материалы KLM</span></article>`;
 qs('#meetingList').innerHTML=meetingPlan.map(m=>{let p=projects.find(project=>project.id===m.projectId),c=customerContact(p),email=c.email?`<a href="mailto:${c.email}" onclick="event.stopPropagation()">Написать заказчику →</a>`:`<a href="${c.source}" target="_blank" rel="noopener" onclick="event.stopPropagation()">Открыть канал →</a>`;return `<article class="meeting-card" data-id="${p.id}" role="button" tabindex="0" aria-label="Открыть проект ${p.name}"><div class="meeting-date"><b>${m.date.slice(0,5)}</b><span>${m.time}</span></div><div class="meeting-main"><div class="meeting-title"><span class="sector">${p.sector}</span><span class="meeting-status status-${m.status==='Контакт установлен'?'ready':m.status==='Подготовка'?'prep':'planned'}">${m.status}</span></div><h3>${p.name}</h3><p class="meeting-company">${c.name} · ${c.company}</p><strong>${m.objective}</strong><p>${m.agenda}</p><div class="meeting-meta"><span>Формат: <b>${m.format}</b></span><span>Ответственный: <b>${m.owner}</b></span>${email}</div></div></article>`}).join('');bindProjectCards();
}
function bindProjectCards(){qsa('[data-id]').forEach(el=>{el.onclick=()=>openProject(el.dataset.id);el.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openProject(el.dataset.id)}}})}
function openProject(id){let p=projects.find(x=>x.id===id);if(!p)return;let c=customerContact(p);qs('#dialogContent').innerHTML=`<div class="dialog-body"><span class="sector">${p.sector} · ${p.id}</span><h2 id="projectDialogTitle">${p.name}</h2><p class="meta">⌖ ${p.city} · ${p.region} · обновлено ${p.updated}</p><div class="dialog-score"><div><small>ПРИОРИТЕТ</small><b>${p.score}/100</b></div><div><small>ДОСТОВЕРНОСТЬ</small><b>Класс ${p.confidence}</b></div><div><small>ИНВЕСТИЦИИ</small><b>${p.investment}</b></div></div><div class="dialog-section"><h3>Почему это интересно KLM</h3><p>${p.potential}</p></div><div class="dialog-section"><h3>Доказательство</h3><p>${p.evidence}</p><a class="source-link" target="_blank" rel="noopener" href="${p.source}">Открыть первичный источник ↗</a></div><div class="dialog-section"><h3>Следующее действие</h3><p>→ ${p.next}</p></div><div class="dialog-section"><h3>Контакт со стороны заказчика</h3>${customerContactMarkup(c)}</div></div>`;qs('#projectDialog').showModal()}
function route(){let id=location.hash.slice(1)||'landing';if(!qs('#'+id))id='landing';document.body.classList.toggle('landing-mode',id==='landing');qsa('.view').forEach(v=>v.classList.toggle('active',v.id===id));qsa('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.view===id));window.scrollTo(0,0);qs('#sidebar').classList.remove('open')}
function showToast(){qs('#toast').classList.add('show');setTimeout(()=>qs('#toast').classList.remove('show'),3300)}
function exportCsv(){let rows=[['ID','Проект','Отрасль','Регион','Стадия','Приоритет','Достоверность','Компания','Следующий шаг','Контакт заказчика','Телефон заказчика','Email заказчика'],...filtered().map(p=>{let c=customerContact(p);return [p.id,p.name,p.sector,p.region,p.stage,p.score,p.confidence,p.company,p.next,c.name,c.phone,c.email]})];let csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='klm-projects-tajikistan.csv';a.click();URL.revokeObjectURL(a.href)}
function bind(){window.addEventListener('hashchange',route);qsa('[data-open-demo]').forEach(b=>b.onclick=()=>location.hash='overview');qsa('[data-go]').forEach(a=>a.onclick=()=>location.hash=a.dataset.go);['#projectSearch','#sectorFilter','#regionFilter','#statusFilter'].forEach(s=>qs(s).addEventListener(s.includes('Search')?'input':'change',renderProjects));qs('#contactSearch').addEventListener('input',renderContacts);qs('#globalSearch').addEventListener('input',()=>{if(qs('#globalSearch').value)location.hash='projects';renderProjects()});qs('#resetFilters').onclick=()=>{qs('#projectSearch').value='';qs('#globalSearch').value='';['#sectorFilter','#regionFilter','#statusFilter'].forEach(s=>qs(s).value='all');renderProjects()};qs('#closeDialog').onclick=()=>qs('#projectDialog').close();qs('#projectDialog').onclick=e=>{if(e.target===qs('#projectDialog'))qs('#projectDialog').close()};qs('#menuBtn').onclick=()=>qs('#sidebar').classList.toggle('open');qs('#scanBtn').onclick=showToast;qs('#scanSourcesBtn').onclick=showToast;qs('#exportBtn').onclick=exportCsv;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();qs('#globalSearch').focus()}})}
init();
